# path.yaml
path:
  - point:
      x: 0.0
      y: 0.0
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 1.0
      y: 0.0
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 2.9
      y: -1.75
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 4.5
      y: -1.75
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 5.3
      y: -3.5
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 5.3
      y: -5.0
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.2
      y: -8.6
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.5
      y: -10.9
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.8
      y: -18.0
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 5.6
      y: -20.1
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 4.1
      y: -20.3
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: -0.5
      y: -20.4
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: -1.96
      y: -21.9
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: -0.8
      y: -23.28
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 0.6
      y: -23.1
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 2.3
      y: -22.6
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 4.95
      y: -22.6
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 5.5
      y: -22.5
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.97
      y: -19.7
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.87
      y: -18.18
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.6
      y: -12.7
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 6.176
      y: -8.417
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 5.7
      y: -6.99
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 5.5
      y: -3.1
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 3.2
      y: -2.1
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 2.0
      y: -1.5
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 1.0
      y: -0.7
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: -0.2
      y: -0.09
      z: 0.0
    velocity:
      linear_x: 0.5
