/RPP_Controller:
  ros__parameters:
    approach_velocity_scaling_dist: 0.6
    desired_linear_vel: 0.5
    lookahead_time: 1.0
    max_angular_accel: 3.2
    max_lookahead_dist: 0.9
    max_robot_pose_search_dist: -1.0
    min_lookahead_dist: 0.3
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    regulated_linear_scaling_min_radius: 0.9
    regulated_linear_scaling_min_speed: 0.25
    rotate_to_heading_angular_vel: 1.0
    rotate_to_heading_min_angle: 0.785
    transform_tolerance: 0.1
    use_interpolation: true
    use_regulated_linear_velocity_scaling: true
    use_rotate_to_heading: true
    use_sim_time: false
    use_velocity_scaled_lookahead_dist: true
